server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://db.wisejia.com:3303/planit
    username: planit
    password: yhs9599
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA ??
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG

# CORS ??
cors:
  allowedOrigins: "http://localhost:3000"
  allowedMethods: "GET,POST,PUT,DELETE,OPTIONS"
